server:
  port: 8083
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/projects?currentSchema=payment
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    services:
      order:
        command:
          topic: order-command-topic

payment:
  mode: true